###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: apexinnovations-webserver
      working_dir: /application/
      volumes:
          - ../website_root:/application/
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./ssl:/ssl/
      ports:
       - "80:80"
       - "443:443"
    redis:
      image: redis:bullseye
      container_name: apexinnovations-redis
      ports:
        - "6379:6379"
      volumes:
        - ./phpdocker/redis/data:/data
    php-fpm:
      build: phpdocker/php-fpm
      container_name: apexinnovations-php-fpm
      working_dir: /application/
      volumes:
        - ../website_root:/application/
        - ./phpdocker/php-fpm/apex-php.ini:/usr/local/etc/php/conf.d/apex-php.ini
        # - ./phpdocker/php-fpm/:etc/php-fpm.d/
    composer_installation:
      container_name: composer_installation
      image: composer
      working_dir: /application/
      volumes:
        - ../website_root:/application/
      command: composer update

